"""
AQSD
Controlled F&O Universe Promotion Manager

Module ID: FNO-002
Version: 1.0.0
Author: AQSD

Purpose
-------
Apply the authoritative CURRENT NSE F&O universe generated by FNO-001
to a NEW Security Master candidate.

IMPORTANT
---------
This module DOES NOT overwrite the existing Security Master.

Historical securities are NEVER deleted.

A security that leaves F&O remains in the Security Master for:
- historical research
- historical price analysis
- participant / derivatives research
- future re-entry tracking
- security identity continuity

Only CURRENT F&O MEMBERSHIP is changed.

Architecture
------------
FNO-001
Official Current NSE F&O Universe
        |
        v
FNO-002
Controlled Promotion Manager
        |
        +--> Current F&O Members
        |
        +--> Former / Excluded F&O Members
        |
        +--> Pending New Securities
        |
        v
Candidate Security Master
        |
        v
Validation
        |
        v
Future Explicit Promotion

Protection
----------
Existing Security Master      : READ ONLY
Historical Securities         : NEVER DELETED
Automatic Replacement         : PROHIBITED
Market Price Database          : NOT MODIFIED
Historical Database            : NOT MODIFIED
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Final

import pandas as pd


# ============================================================
# MODULE IDENTITY
# ============================================================

MODULE_ID: Final[str] = "FNO-002"
MODULE_VERSION: Final[str] = "1.0.0"


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT: Final[Path] = (
    Path(__file__)
    .resolve()
    .parents[2]
)

OUTPUT_DIR: Final[Path] = (
    PROJECT_ROOT
    / "Output"
)


# ============================================================
# INPUT FILES
# ============================================================

SECURITY_MASTER_FILE: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_Security_Master_Enriched.csv"
)

CURRENT_FNO_UNIVERSE_FILE: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_Current_NSE_FNO_Universe.csv"
)

FNO_INCLUSIONS_FILE: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_Current_NSE_FNO_Inclusions.csv"
)

FNO_EXCLUSIONS_FILE: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_Current_NSE_FNO_Exclusions.csv"
)

FNO_SUMMARY_FILE: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_Current_NSE_FNO_Universe_Summary.json"
)


# ============================================================
# OUTPUT FILES
# ============================================================

CANDIDATE_MASTER_CSV: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_Security_Master_FNO_Promoted_Candidate.csv"
)

PROMOTION_AUDIT_CSV: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_FNO_Promotion_Audit.csv"
)

CURRENT_MEMBERS_CSV: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_FNO_Current_Members.csv"
)

FORMER_MEMBERS_CSV: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_FNO_Former_Members.csv"
)

PENDING_INCLUSIONS_CSV: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_FNO_Pending_Security_Onboarding.csv"
)

SUMMARY_JSON: Final[Path] = (
    OUTPUT_DIR
    / "AQSD_FNO_Promotion_Summary.json"
)


# ============================================================
# HELPERS
# ============================================================

def ensure_output_directory() -> None:

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


def normalize_column_name(
    value: object,
) -> str:

    return (
        str(value)
        .strip()
        .lower()
        .replace(" ", "_")
        .replace("-", "_")
        .replace("/", "_")
        .replace(".", "_")
        .replace("(", "")
        .replace(")", "")
    )


def normalize_symbol(
    value: object,
) -> str:

    if pd.isna(value):
        return ""

    symbol = (
        str(value)
        .strip()
        .upper()
    )

    if symbol.startswith("NSE:"):
        symbol = symbol[4:]

    for suffix in (
        "-EQ",
        ".NS",
    ):

        if symbol.endswith(
            suffix
        ):

            symbol = symbol[
                : -len(suffix)
            ]

    aliases = {
        "NIFTY50":
            "NIFTY",

        "NIFTYBANK":
            "BANKNIFTY",

        "NIFTYNEXT50":
            "NIFTYNXT50",
    }

    return aliases.get(
        symbol,
        symbol,
    )


def parse_bool(
    value: object,
) -> bool:

    if pd.isna(value):
        return False

    return (
        str(value)
        .strip()
        .upper()
        in {
            "TRUE",
            "YES",
            "Y",
            "1",
        }
    )


def file_sha256(
    path: Path,
) -> str:

    digest = hashlib.sha256()

    with path.open(
        "rb"
    ) as handle:

        while True:

            chunk = handle.read(
                1024 * 1024
            )

            if not chunk:
                break

            digest.update(
                chunk
            )

    return digest.hexdigest()


def separator() -> None:

    print(
        "=" * 100
    )


def sub_separator() -> None:

    print(
        "-" * 100
    )


# ============================================================
# INPUT VALIDATION
# ============================================================

def validate_input_files() -> None:

    required_files = [
        SECURITY_MASTER_FILE,
        CURRENT_FNO_UNIVERSE_FILE,
        FNO_SUMMARY_FILE,
    ]

    missing_files = [
        path
        for path in required_files
        if not path.exists()
    ]

    if missing_files:

        raise FileNotFoundError(
            "Required FNO-002 input files missing: "
            + ", ".join(
                str(path)
                for path in missing_files
            )
        )


# ============================================================
# LOAD SECURITY MASTER
# ============================================================

def load_security_master() -> pd.DataFrame:

    dataframe = pd.read_csv(
        SECURITY_MASTER_FILE,
        low_memory=False,
    )

    dataframe.columns = [
        normalize_column_name(
            column
        )
        for column in dataframe.columns
    ]

    required_columns = {
        "security_id",
        "symbol",
    }

    missing = (
        required_columns
        - set(
            dataframe.columns
        )
    )

    if missing:

        raise RuntimeError(
            "Security Master missing required columns: "
            + ", ".join(
                sorted(
                    missing
                )
            )
        )

    dataframe[
        "security_id"
    ] = (
        dataframe[
            "security_id"
        ]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    dataframe[
        "symbol"
    ] = (
        dataframe[
            "symbol"
        ]
        .map(
            normalize_symbol
        )
    )

    return dataframe


# ============================================================
# LOAD CURRENT F&O UNIVERSE
# ============================================================

def load_current_fno_universe() -> pd.DataFrame:

    dataframe = pd.read_csv(
        CURRENT_FNO_UNIVERSE_FILE,
        low_memory=False,
    )

    dataframe.columns = [
        normalize_column_name(
            column
        )
        for column in dataframe.columns
    ]

    if "symbol" not in dataframe.columns:

        raise RuntimeError(
            "Current F&O universe has no symbol column."
        )

    dataframe[
        "symbol"
    ] = (
        dataframe[
            "symbol"
        ]
        .map(
            normalize_symbol
        )
    )

    dataframe = dataframe[
        dataframe[
            "symbol"
        ].ne("")
    ].copy()

    dataframe = (
        dataframe
        .drop_duplicates(
            subset=[
                "symbol",
            ],
            keep="first",
        )
        .reset_index(
            drop=True
        )
    )

    return dataframe


# ============================================================
# LOAD FNO-001 SUMMARY
# ============================================================

def load_fno001_summary() -> dict[str, object]:

    return json.loads(
        FNO_SUMMARY_FILE.read_text(
            encoding="utf-8",
        )
    )


# ============================================================
# VALIDATE FNO-001
# ============================================================

def validate_fno001_summary(
    summary: dict[str, object],
) -> None:

    status = str(
        summary.get(
            "status",
            "",
        )
    ).strip().upper()

    if status != "SUCCESS":

        raise RuntimeError(
            "FNO-001 status is not SUCCESS."
        )

    reconciliation_ok = bool(
        summary.get(
            "reconciliation_ok",
            False,
        )
    )

    if not reconciliation_ok:

        raise RuntimeError(
            "FNO-001 reconciliation did not pass."
        )

    critical_issues = int(
        summary.get(
            "critical_issues",
            0,
        )
    )

    if critical_issues != 0:

        raise RuntimeError(
            "FNO-001 contains critical issues."
        )


# ============================================================
# MASTER STRUCTURAL VALIDATION
# ============================================================

def validate_security_master(
    dataframe: pd.DataFrame,
) -> dict[str, int]:

    duplicate_security_ids = int(
        dataframe.duplicated(
            subset=[
                "security_id",
            ],
            keep=False,
        ).sum()
    )

    duplicate_symbols = int(
        dataframe.duplicated(
            subset=[
                "symbol",
            ],
            keep=False,
        ).sum()
    )

    blank_security_ids = int(
        dataframe[
            "security_id"
        ]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    blank_symbols = int(
        dataframe[
            "symbol"
        ]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    critical_issues = (
        duplicate_security_ids
        + duplicate_symbols
        + blank_security_ids
        + blank_symbols
    )

    return {
        "duplicate_security_ids":
            duplicate_security_ids,

        "duplicate_symbols":
            duplicate_symbols,

        "blank_security_ids":
            blank_security_ids,

        "blank_symbols":
            blank_symbols,

        "critical_issues":
            critical_issues,
    }


# ============================================================
# DETECT NEW CURRENT SYMBOLS
# ============================================================

def detect_pending_inclusions(
    security_master: pd.DataFrame,
    current_universe: pd.DataFrame,
) -> pd.DataFrame:

    master_symbols = set(
        security_master[
            "symbol"
        ]
    )

    current_symbols = set(
        current_universe[
            "symbol"
        ]
    )

    pending_symbols = (
        current_symbols
        - master_symbols
    )

    pending = current_universe[
        current_universe[
            "symbol"
        ].isin(
            pending_symbols
        )
    ].copy()

    if not pending.empty:

        pending[
            "onboarding_status"
        ] = "PENDING_SECURITY_MASTER_ONBOARDING"

        pending[
            "security_id_status"
        ] = "NOT_ASSIGNED"

        pending[
            "automatic_promotion"
        ] = False

    return pending


# ============================================================
# BUILD CANDIDATE SECURITY MASTER
# ============================================================

def build_candidate_master(
    security_master: pd.DataFrame,
    current_universe: pd.DataFrame,
    *,
    as_of_date: str,
) -> pd.DataFrame:

    candidate = security_master.copy()

    current_symbols = set(
        current_universe[
            "symbol"
        ]
    )

    # --------------------------------------------------------
    # Preserve prior membership before changing anything
    # --------------------------------------------------------

    if "is_fno" in candidate.columns:

        previous_fno = (
            candidate[
                "is_fno"
            ]
            .map(
                parse_bool
            )
        )

    elif "fno_flag" in candidate.columns:

        previous_fno = (
            candidate[
                "fno_flag"
            ]
            .map(
                parse_bool
            )
        )

    else:

        previous_fno = pd.Series(
            False,
            index=candidate.index,
        )

    candidate[
        "previous_fno_member"
    ] = previous_fno

    # --------------------------------------------------------
    # Authoritative current membership
    # --------------------------------------------------------

    candidate[
        "current_fno_member"
    ] = (
        candidate[
            "symbol"
        ]
        .isin(
            current_symbols
        )
    )

    # --------------------------------------------------------
    # Existing AQSD compatibility fields
    # --------------------------------------------------------

    candidate[
        "is_fno"
    ] = (
        candidate[
            "current_fno_member"
        ]
    )

    candidate[
        "fno_flag"
    ] = candidate[
        "current_fno_member"
    ].map(
        {
            True: "YES",
            False: "NO",
        }
    )

    # --------------------------------------------------------
    # Membership classification
    # --------------------------------------------------------

    def membership_change(
        row: pd.Series,
    ) -> str:

        previous = bool(
            row[
                "previous_fno_member"
            ]
        )

        current = bool(
            row[
                "current_fno_member"
            ]
        )

        if previous and current:
            return "UNCHANGED_CURRENT"

        if previous and not current:
            return "EXCLUDED_FROM_CURRENT_FNO"

        if not previous and current:
            return "NEW_CURRENT_FNO"

        return "NON_FNO"

    candidate[
        "fno_membership_change"
    ] = candidate.apply(
        membership_change,
        axis=1,
    )

    candidate[
        "fno_membership_status"
    ] = candidate[
        "current_fno_member"
    ].map(
        {
            True: "CURRENT_FNO",
            False: "NOT_CURRENT_FNO",
        }
    )

    candidate[
        "fno_membership_asof"
    ] = as_of_date

    candidate[
        "fno_membership_source"
    ] = "NSE_FO_MII_CONTRACT_MASTER"

    candidate[
        "fno_membership_module"
    ] = MODULE_ID

    candidate[
        "fno_membership_version"
    ] = MODULE_VERSION

    candidate[
        "fno_membership_updated_at"
    ] = (
        datetime.now()
        .astimezone()
        .isoformat(
            timespec="seconds"
        )
    )

    # --------------------------------------------------------
    # IMPORTANT:
    # active_flag is NOT modified.
    #
    # A stock can remain an active NSE security even when
    # removed from the F&O segment.
    # --------------------------------------------------------

    return candidate


# ============================================================
# BUILD AUDIT
# ============================================================

def build_promotion_audit(
    original: pd.DataFrame,
    candidate: pd.DataFrame,
) -> pd.DataFrame:

    audit = pd.DataFrame()

    audit[
        "security_id"
    ] = candidate[
        "security_id"
    ]

    audit[
        "symbol"
    ] = candidate[
        "symbol"
    ]

    audit[
        "previous_fno_member"
    ] = candidate[
        "previous_fno_member"
    ]

    audit[
        "current_fno_member"
    ] = candidate[
        "current_fno_member"
    ]

    audit[
        "fno_membership_change"
    ] = candidate[
        "fno_membership_change"
    ]

    audit[
        "membership_asof"
    ] = candidate[
        "fno_membership_asof"
    ]

    audit[
        "source"
    ] = candidate[
        "fno_membership_source"
    ]

    audit[
        "module"
    ] = MODULE_ID

    audit[
        "version"
    ] = MODULE_VERSION

    audit[
        "candidate_only"
    ] = True

    return audit


# ============================================================
# VALIDATE CANDIDATE
# ============================================================

def validate_candidate(
    original: pd.DataFrame,
    candidate: pd.DataFrame,
    current_universe: pd.DataFrame,
    pending_inclusions: pd.DataFrame,
) -> dict[str, object]:

    original_rows = int(
        len(
            original
        )
    )

    candidate_rows = int(
        len(
            candidate
        )
    )

    row_count_preserved = (
        original_rows
        == candidate_rows
    )

    original_ids = set(
        original[
            "security_id"
        ]
    )

    candidate_ids = set(
        candidate[
            "security_id"
        ]
    )

    security_ids_preserved = (
        original_ids
        == candidate_ids
    )

    original_symbols = set(
        original[
            "symbol"
        ]
    )

    candidate_symbols = set(
        candidate[
            "symbol"
        ]
    )

    symbols_preserved = (
        original_symbols
        == candidate_symbols
    )

    current_expected = int(
        len(
            current_universe
        )
        - len(
            pending_inclusions
        )
    )

    current_candidate = int(
        candidate[
            "current_fno_member"
        ].sum()
    )

    current_membership_matches = (
        current_candidate
        == current_expected
    )

    excluded_count = int(
        candidate[
            "fno_membership_change"
        ]
        .eq(
            "EXCLUDED_FROM_CURRENT_FNO"
        )
        .sum()
    )

    new_current_count = int(
        candidate[
            "fno_membership_change"
        ]
        .eq(
            "NEW_CURRENT_FNO"
        )
        .sum()
    )

    duplicate_security_ids = int(
        candidate.duplicated(
            subset=[
                "security_id",
            ],
            keep=False,
        ).sum()
    )

    duplicate_symbols = int(
        candidate.duplicated(
            subset=[
                "symbol",
            ],
            keep=False,
        ).sum()
    )

    critical_issues = 0

    if not row_count_preserved:
        critical_issues += 1

    if not security_ids_preserved:
        critical_issues += 1

    if not symbols_preserved:
        critical_issues += 1

    if not current_membership_matches:
        critical_issues += 1

    critical_issues += (
        duplicate_security_ids
        + duplicate_symbols
    )

    return {
        "original_rows":
            original_rows,

        "candidate_rows":
            candidate_rows,

        "row_count_preserved":
            row_count_preserved,

        "security_ids_preserved":
            security_ids_preserved,

        "symbols_preserved":
            symbols_preserved,

        "expected_current_members":
            current_expected,

        "candidate_current_members":
            current_candidate,

        "current_membership_matches":
            current_membership_matches,

        "excluded_members":
            excluded_count,

        "new_current_members":
            new_current_count,

        "pending_inclusions":
            int(
                len(
                    pending_inclusions
                )
            ),

        "duplicate_security_ids":
            duplicate_security_ids,

        "duplicate_symbols":
            duplicate_symbols,

        "critical_issues":
            critical_issues,
    }


# ============================================================
# WRITE OUTPUTS
# ============================================================

def write_outputs(
    candidate: pd.DataFrame,
    audit: pd.DataFrame,
    pending_inclusions: pd.DataFrame,
    summary: dict[str, object],
) -> None:

    candidate.to_csv(
        CANDIDATE_MASTER_CSV,
        index=False,
        encoding="utf-8-sig",
    )

    audit.to_csv(
        PROMOTION_AUDIT_CSV,
        index=False,
        encoding="utf-8-sig",
    )

    candidate[
        candidate[
            "current_fno_member"
        ]
    ].to_csv(
        CURRENT_MEMBERS_CSV,
        index=False,
        encoding="utf-8-sig",
    )

    candidate[
        candidate[
            "fno_membership_change"
        ].eq(
            "EXCLUDED_FROM_CURRENT_FNO"
        )
    ].to_csv(
        FORMER_MEMBERS_CSV,
        index=False,
        encoding="utf-8-sig",
    )

    pending_inclusions.to_csv(
        PENDING_INCLUSIONS_CSV,
        index=False,
        encoding="utf-8-sig",
    )

    SUMMARY_JSON.write_text(
        json.dumps(
            summary,
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )


# ============================================================
# RUN MANAGER
# ============================================================

def run_manager() -> dict[str, object]:

    ensure_output_directory()

    validate_input_files()

    source_hash_before = file_sha256(
        SECURITY_MASTER_FILE
    )

    fno001_summary = (
        load_fno001_summary()
    )

    validate_fno001_summary(
        fno001_summary
    )

    security_master = (
        load_security_master()
    )

    master_validation = (
        validate_security_master(
            security_master
        )
    )

    if (
        master_validation[
            "critical_issues"
        ]
        != 0
    ):

        raise RuntimeError(
            "Source Security Master failed structural validation."
        )

    current_universe = (
        load_current_fno_universe()
    )

    pending_inclusions = (
        detect_pending_inclusions(
            security_master,
            current_universe,
        )
    )

    as_of_date = str(
        fno001_summary.get(
            "contract_date",
            "",
        )
    )

    if not as_of_date:

        raise RuntimeError(
            "FNO-001 contract date missing."
        )

    candidate = build_candidate_master(
        security_master,
        current_universe,
        as_of_date=as_of_date,
    )

    audit = build_promotion_audit(
        security_master,
        candidate,
    )

    validation = validate_candidate(
        security_master,
        candidate,
        current_universe,
        pending_inclusions,
    )

    if (
        validation[
            "critical_issues"
        ]
        != 0
    ):

        raise RuntimeError(
            "Candidate Security Master failed validation."
        )

    source_hash_after = file_sha256(
        SECURITY_MASTER_FILE
    )

    source_untouched = (
        source_hash_before
        == source_hash_after
    )

    if not source_untouched:

        raise RuntimeError(
            "Source Security Master changed during FNO-002."
        )

    summary = {
        "module_id":
            MODULE_ID,

        "module_version":
            MODULE_VERSION,

        "generated_at":
            datetime.now()
            .astimezone()
            .isoformat(
                timespec="seconds"
            ),

        "fno_contract_date":
            as_of_date,

        "official_current_fno_universe":
            int(
                len(
                    current_universe
                )
            ),

        "source_security_master_rows":
            validation[
                "original_rows"
            ],

        "candidate_security_master_rows":
            validation[
                "candidate_rows"
            ],

        "current_fno_members":
            validation[
                "candidate_current_members"
            ],

        "former_fno_members":
            validation[
                "excluded_members"
            ],

        "new_current_members":
            validation[
                "new_current_members"
            ],

        "pending_security_onboarding":
            validation[
                "pending_inclusions"
            ],

        "row_count_preserved":
            validation[
                "row_count_preserved"
            ],

        "security_ids_preserved":
            validation[
                "security_ids_preserved"
            ],

        "symbols_preserved":
            validation[
                "symbols_preserved"
            ],

        "current_membership_matches":
            validation[
                "current_membership_matches"
            ],

        "duplicate_security_ids":
            validation[
                "duplicate_security_ids"
            ],

        "duplicate_symbols":
            validation[
                "duplicate_symbols"
            ],

        "critical_issues":
            validation[
                "critical_issues"
            ],

        "source_security_master_sha256":
            source_hash_before,

        "source_security_master_untouched":
            source_untouched,

        "candidate_master":
            str(
                CANDIDATE_MASTER_CSV
            ),

        "promotion_audit":
            str(
                PROMOTION_AUDIT_CSV
            ),

        "current_members_file":
            str(
                CURRENT_MEMBERS_CSV
            ),

        "former_members_file":
            str(
                FORMER_MEMBERS_CSV
            ),

        "pending_inclusions_file":
            str(
                PENDING_INCLUSIONS_CSV
            ),

        "source_security_master_modified":
            False,

        "market_price_database_modified":
            False,

        "historical_database_modified":
            False,

        "automatic_replacement":
            False,

        "promotion_status":
            "CANDIDATE_ONLY",

        "status":
            "SUCCESS",
    }

    write_outputs(
        candidate,
        audit,
        pending_inclusions,
        summary,
    )

    return summary


# ============================================================
# DISPLAY
# ============================================================

def display_summary(
    summary: dict[str, object],
) -> None:

    print()
    separator()

    print(
        "AQSD CONTROLLED F&O UNIVERSE PROMOTION MANAGER"
    )

    separator()

    print(
        f"Module                         : "
        f"{summary['module_id']}"
    )

    print(
        f"Version                        : "
        f"{summary['module_version']}"
    )

    print(
        f"F&O Contract Date              : "
        f"{summary['fno_contract_date']}"
    )

    sub_separator()

    print(
        f"Official Current F&O Universe  : "
        f"{int(summary['official_current_fno_universe']):,}"
    )

    print(
        f"Source Security Master Rows    : "
        f"{int(summary['source_security_master_rows']):,}"
    )

    print(
        f"Candidate Master Rows          : "
        f"{int(summary['candidate_security_master_rows']):,}"
    )

    sub_separator()

    print(
        f"Current F&O Members            : "
        f"{int(summary['current_fno_members']):,}"
    )

    print(
        f"Former F&O Members             : "
        f"{int(summary['former_fno_members']):,}"
    )

    print(
        f"New Current Members            : "
        f"{int(summary['new_current_members']):,}"
    )

    print(
        f"Pending Security Onboarding    : "
        f"{int(summary['pending_security_onboarding']):,}"
    )

    sub_separator()

    print(
        f"Row Count Preserved            : "
        f"{summary['row_count_preserved']}"
    )

    print(
        f"Security IDs Preserved         : "
        f"{summary['security_ids_preserved']}"
    )

    print(
        f"Symbols Preserved              : "
        f"{summary['symbols_preserved']}"
    )

    print(
        f"Current Membership Matches     : "
        f"{summary['current_membership_matches']}"
    )

    print(
        f"Duplicate Security IDs         : "
        f"{int(summary['duplicate_security_ids']):,}"
    )

    print(
        f"Duplicate Symbols              : "
        f"{int(summary['duplicate_symbols']):,}"
    )

    print(
        f"Critical Issues                : "
        f"{int(summary['critical_issues']):,}"
    )

    sub_separator()

    print(
        f"Candidate Master               : "
        f"{summary['candidate_master']}"
    )

    print(
        f"Promotion Audit                : "
        f"{summary['promotion_audit']}"
    )

    print(
        f"Current Members                : "
        f"{summary['current_members_file']}"
    )

    print(
        f"Former Members                 : "
        f"{summary['former_members_file']}"
    )

    print(
        f"Pending Inclusions             : "
        f"{summary['pending_inclusions_file']}"
    )

    sub_separator()

    print(
        f"Source Master Untouched        : "
        f"{summary['source_security_master_untouched']}"
    )

    print(
        "Existing Security Master       : READ ONLY / UNCHANGED"
    )

    print(
        "Historical Securities          : PRESERVED"
    )

    print(
        "Market Price Database          : NOT MODIFIED"
    )

    print(
        "Historical Database            : NOT MODIFIED"
    )

    print(
        "Automatic Replacement          : PROHIBITED"
    )

    print(
        f"Promotion Status               : "
        f"{summary['promotion_status']}"
    )

    sub_separator()

    print(
        f"Status                         : "
        f"{summary['status']}"
    )

    separator()


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    try:

        summary = run_manager()

        display_summary(
            summary
        )

    except Exception as exc:

        print()
        separator()

        print(
            "AQSD CONTROLLED F&O UNIVERSE PROMOTION MANAGER"
        )

        separator()

        print(
            "Status                         : FAILED"
        )

        print(
            f"Reason                         : "
            f"{type(exc).__name__}: {exc}"
        )

        print(
            "Existing Security Master       : NOT MODIFIED"
        )

        print(
            "Market Price Database          : NOT MODIFIED"
        )

        print(
            "Automatic Replacement          : PROHIBITED"
        )

        separator()

        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()