"""
AQSD
Sector Rotation Engine

Module : MBI-007
Version: 1.0.0
Author : AQSD

Description
-----------
Compares saved AQSD Sector Strength reports across trading sessions
and identifies changes in sector leadership.

The engine calculates:

- Current sector rank
- Previous-session rank
- Weekly-reference rank
- Daily rank change
- Weekly rank change
- Daily score change
- Weekly score change
- New leaders
- Persistent leaders
- Emerging sectors
- Losing leadership
- New laggards
- Persistent laggards
- Rotation direction
- Rotation breadth
- Rotation speed
- Leadership stability
- Sector cycle
- Rotation risk
- Final explainable rotation conclusion

Inputs
------
Output/Sector_Strength/sector_strength_summary_YYYYMMDD.csv

These files are generated by:

    Scripts.aqsd_intelligence.sector_strength_engine

Important
---------
This module provides analytical decision support only.

It does not generate BUY, SELL or SHORT instructions.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Final

import pandas as pd


# ==========================================================
# MODULE SETTINGS
# ==========================================================

MODULE_ID: Final[str] = "MBI-007"
MODULE_VERSION: Final[str] = "1.0.0"

BASE_DIR: Final[Path] = Path(__file__).resolve().parents[2]

SECTOR_STRENGTH_DIRECTORY: Final[Path] = (
    BASE_DIR
    / "Output"
    / "Sector_Strength"
)

OUTPUT_DIRECTORY: Final[Path] = (
    BASE_DIR
    / "Output"
    / "Sector_Rotation"
)

DEFAULT_WEEKLY_LOOKBACK_SESSIONS: Final[int] = 5

LEADER_RANK_LIMIT: Final[int] = 3
LEADING_RANK_LIMIT: Final[int] = 5
LAGGARD_RANK_COUNT: Final[int] = 3

MINIMUM_MEANINGFUL_RANK_CHANGE: Final[int] = 2
MINIMUM_MEANINGFUL_SCORE_CHANGE: Final[int] = 3


# ==========================================================
# RESULT MODELS
# ==========================================================

@dataclass(frozen=True)
class SectorRotationRecord:
    """
    Rotation result for one sector.
    """

    sector: str

    current_rank: int
    previous_rank: int | None
    weekly_rank: int | None

    daily_rank_change: int | None
    weekly_rank_change: int | None

    current_score: int
    previous_score: int | None
    weekly_score: int | None

    daily_score_change: int | None
    weekly_score_change: int | None

    current_strength: str
    current_trend: str
    current_momentum: str
    current_rotation: str
    current_leadership: str
    current_risk_level: str
    current_confidence: int

    rotation_state: str
    sector_cycle: str
    leadership_status: str
    rotation_speed: str
    rotation_risk: str

    expected_behaviour: str
    concise_summary: str
    explanation: str

    warnings: tuple[str, ...]
    status: str


@dataclass(frozen=True)
class SectorRotationEngineResult:
    """
    Complete MBI-007 result.
    """

    requested_date: date
    analysis_date: date
    previous_date: date | None
    weekly_reference_date: date | None

    sectors_analysed: int

    new_leaders: tuple[SectorRotationRecord, ...]
    persistent_leaders: tuple[SectorRotationRecord, ...]
    emerging_sectors: tuple[SectorRotationRecord, ...]
    losing_leadership: tuple[SectorRotationRecord, ...]
    new_laggards: tuple[SectorRotationRecord, ...]
    persistent_laggards: tuple[SectorRotationRecord, ...]
    stable_sectors: tuple[SectorRotationRecord, ...]

    improving_sectors: int
    deteriorating_sectors: int
    stable_sector_count: int

    rotation_direction: str
    rotation_breadth: str
    rotation_speed: str
    leadership_stability: str
    dominant_sector_cycle: str

    rotation_risk_score: int
    rotation_risk_level: str

    confidence: int
    expected_behaviour: str
    master_conclusion: str
    concise_summary: str
    explanation: str

    records: tuple[SectorRotationRecord, ...]
    warnings: tuple[str, ...]

    csv_file: Path | None
    excel_file: Path | None

    status: str


# ==========================================================
# GENERAL HELPERS
# ==========================================================

def clamp_score(
    value: float,
) -> int:
    """
    Restrict a value to the range 0-100.
    """

    return max(
        0,
        min(
            round(value),
            100,
        ),
    )


def safe_int(
    value: object,
    default: int = 0,
) -> int:
    """
    Convert a value to integer safely.
    """

    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass

    try:
        return int(
            round(
                float(value)
            )
        )

    except (
        TypeError,
        ValueError,
    ):
        return default


def normalize_text(
    value: object,
    default: str = "UNKNOWN",
) -> str:
    """
    Normalize a text value.
    """

    if value is None:
        return default

    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass

    text = str(value).strip().upper()

    return text or default


def format_optional_change(
    value: int | None,
) -> str:
    """
    Format an optional signed integer.
    """

    if value is None:
        return "NOT AVAILABLE"

    return f"{value:+d}"


def extract_date_from_filename(
    file_path: Path,
) -> date | None:
    """
    Extract YYYYMMDD from a sector-strength filename.
    """

    match = re.search(
        r"(\d{8})",
        file_path.stem,
    )

    if match is None:
        return None

    try:
        return datetime.strptime(
            match.group(1),
            "%Y%m%d",
        ).date()

    except ValueError:
        return None


# ==========================================================
# FILE DISCOVERY
# ==========================================================

def discover_sector_strength_files() -> dict[date, Path]:
    """
    Discover saved sector-strength summary files.
    """

    files: dict[date, Path] = {}

    if not SECTOR_STRENGTH_DIRECTORY.exists():
        return files

    for file_path in SECTOR_STRENGTH_DIRECTORY.glob(
        "sector_strength_summary_*.csv"
    ):
        file_date = extract_date_from_filename(
            file_path
        )

        if file_date is not None:
            files[file_date] = file_path

    return files


def select_analysis_dates(
    *,
    requested_date: date,
    available_dates: list[date],
    weekly_lookback_sessions: int,
) -> tuple[
    date,
    date | None,
    date | None,
]:
    """
    Select current, previous and weekly-reference dates.
    """

    eligible_dates = sorted(
        value
        for value in available_dates
        if value <= requested_date
    )

    if not eligible_dates:
        raise RuntimeError(
            "No sector-strength summary is available on or before "
            f"{requested_date}."
        )

    analysis_date = eligible_dates[-1]

    previous_date = (
        eligible_dates[-2]
        if len(eligible_dates) >= 2
        else None
    )

    weekly_reference_date: date | None = None

    weekly_position = (
        len(eligible_dates)
        - 1
        - weekly_lookback_sessions
    )

    if weekly_position >= 0:
        weekly_reference_date = eligible_dates[
            weekly_position
        ]

    return (
        analysis_date,
        previous_date,
        weekly_reference_date,
    )


# ==========================================================
# REPORT READING
# ==========================================================

def normalize_report_columns(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """
    Normalize sector-strength report headings.
    """

    result = dataframe.copy()

    result.columns = [
        re.sub(
            r"_+",
            "_",
            re.sub(
                r"[^A-Za-z0-9]+",
                "_",
                str(column).strip(),
            ),
        ).strip("_")
        for column in result.columns
    ]

    aliases = {
        "RANK": "Rank",
        "SECTOR": "Sector",
        "BREADTH_SCORE": "Breadth_Score",
        "SCORE": "Breadth_Score",
        "STRENGTH": "Strength",
        "TREND": "Trend",
        "MOMENTUM": "Momentum",
        "ROTATION": "Rotation",
        "LEADERSHIP": "Leadership",
        "RISK_LEVEL": "Risk_Level",
        "CONFIDENCE": "Confidence",
    }

    rename_map: dict[str, str] = {}

    for column in result.columns:
        key = str(column).upper()

        if key in aliases:
            rename_map[column] = aliases[key]

    return result.rename(
        columns=rename_map
    )


def read_sector_strength_report(
    file_path: Path,
) -> pd.DataFrame:
    """
    Read one saved sector-strength CSV.
    """

    dataframe = pd.read_csv(
        file_path,
        low_memory=False,
    )

    if dataframe.empty:
        raise RuntimeError(
            f"Sector-strength file is empty: {file_path}"
        )

    dataframe = normalize_report_columns(
        dataframe
    )

    required_columns = {
        "Rank",
        "Sector",
        "Breadth_Score",
    }

    missing_columns = (
        required_columns
        - set(dataframe.columns)
    )

    if missing_columns:
        raise KeyError(
            "Sector-strength report is missing columns: "
            + ", ".join(
                sorted(missing_columns)
            )
        )

    optional_defaults: dict[str, object] = {
        "Strength": "UNKNOWN",
        "Trend": "UNKNOWN",
        "Momentum": "UNKNOWN",
        "Rotation": "UNKNOWN",
        "Leadership": "UNKNOWN",
        "Risk_Level": "UNKNOWN",
        "Confidence": 0,
    }

    for column, default in optional_defaults.items():
        if column not in dataframe.columns:
            dataframe[column] = default

    dataframe["Sector"] = (
        dataframe["Sector"]
        .fillna("UNKNOWN")
        .astype(str)
        .str.strip()
        .str.upper()
    )

    dataframe["Rank"] = pd.to_numeric(
        dataframe["Rank"],
        errors="coerce",
    )

    dataframe["Breadth_Score"] = pd.to_numeric(
        dataframe["Breadth_Score"],
        errors="coerce",
    )

    dataframe["Confidence"] = pd.to_numeric(
        dataframe["Confidence"],
        errors="coerce",
    ).fillna(0)

    for column in (
        "Strength",
        "Trend",
        "Momentum",
        "Rotation",
        "Leadership",
        "Risk_Level",
    ):
        dataframe[column] = (
            dataframe[column]
            .fillna("UNKNOWN")
            .astype(str)
            .str.strip()
            .str.upper()
        )

    dataframe = dataframe.dropna(
        subset=[
            "Rank",
            "Breadth_Score",
        ]
    )

    dataframe = dataframe.loc[
        dataframe["Sector"].ne("UNKNOWN")
    ].copy()

    dataframe["Rank"] = (
        dataframe["Rank"]
        .round()
        .astype(int)
    )

    dataframe["Breadth_Score"] = (
        dataframe["Breadth_Score"]
        .round()
        .astype(int)
    )

    dataframe["Confidence"] = (
        dataframe["Confidence"]
        .round()
        .astype(int)
    )

    dataframe = dataframe.drop_duplicates(
        subset=["Sector"],
        keep="last",
    )

    return dataframe.sort_values(
        "Rank"
    ).reset_index(
        drop=True
    )


def build_sector_map(
    dataframe: pd.DataFrame | None,
) -> dict[str, pd.Series]:
    """
    Convert a sector report to a sector-indexed map.
    """

    if dataframe is None:
        return {}

    return {
        str(row["Sector"]): row
        for _, row
        in dataframe.iterrows()
    }


# ==========================================================
# CHANGE HELPERS
# ==========================================================

def calculate_rank_change(
    *,
    current_rank: int,
    previous_rank: int | None,
) -> int | None:
    """
    Calculate rank improvement.

    Positive value means the sector moved higher in rank.

    Example
    -------
    Previous rank 8, current rank 3:

        8 - 3 = +5
    """

    if previous_rank is None:
        return None

    return previous_rank - current_rank


def calculate_score_change(
    *,
    current_score: int,
    previous_score: int | None,
) -> int | None:
    """
    Calculate sector-score change.
    """

    if previous_score is None:
        return None

    return current_score - previous_score


def is_current_leader(
    rank: int,
) -> bool:
    """
    Return True for a top-three sector.
    """

    return rank <= LEADER_RANK_LIMIT


def is_current_leading_group(
    rank: int,
) -> bool:
    """
    Return True for a top-five sector.
    """

    return rank <= LEADING_RANK_LIMIT


def is_laggard(
    *,
    rank: int,
    total_sectors: int,
) -> bool:
    """
    Return True for a bottom-ranked sector.
    """

    threshold = max(
        1,
        total_sectors
        - LAGGARD_RANK_COUNT
        + 1,
    )

    return rank >= threshold


# ==========================================================
# ROTATION CLASSIFICATION
# ==========================================================

def determine_rotation_state(
    *,
    current_rank: int,
    previous_rank: int | None,
    weekly_rank: int | None,
    current_score: int,
    daily_score_change: int | None,
    weekly_score_change: int | None,
    total_sectors: int,
) -> str:
    """
    Classify the current rotation state.
    """

    current_leader = is_current_leader(
        current_rank
    )

    previous_leader = (
        is_current_leader(previous_rank)
        if previous_rank is not None
        else False
    )

    current_laggard = is_laggard(
        rank=current_rank,
        total_sectors=total_sectors,
    )

    previous_laggard = (
        is_laggard(
            rank=previous_rank,
            total_sectors=total_sectors,
        )
        if previous_rank is not None
        else False
    )

    if (
        current_leader
        and previous_rank is not None
        and not previous_leader
    ):
        return "NEW LEADER"

    if (
        current_leader
        and previous_leader
    ):
        return "PERSISTENT LEADER"

    if (
        current_laggard
        and previous_rank is not None
        and not previous_laggard
    ):
        return "NEW LAGGARD"

    if (
        current_laggard
        and previous_laggard
    ):
        return "PERSISTENT LAGGARD"

    if (
        previous_leader
        and not current_leader
    ):
        return "LOSING LEADERSHIP"

    positive_daily = (
        daily_score_change is not None
        and daily_score_change
        >= MINIMUM_MEANINGFUL_SCORE_CHANGE
    )

    positive_weekly = (
        weekly_score_change is not None
        and weekly_score_change
        >= MINIMUM_MEANINGFUL_SCORE_CHANGE
    )

    meaningful_rank_improvement = (
        previous_rank is not None
        and previous_rank - current_rank
        >= MINIMUM_MEANINGFUL_RANK_CHANGE
    )

    if (
        current_score >= 50
        and (
            meaningful_rank_improvement
            or positive_daily
            or positive_weekly
        )
    ):
        return "EMERGING"

    negative_daily = (
        daily_score_change is not None
        and daily_score_change
        <= -MINIMUM_MEANINGFUL_SCORE_CHANGE
    )

    meaningful_rank_decline = (
        previous_rank is not None
        and previous_rank - current_rank
        <= -MINIMUM_MEANINGFUL_RANK_CHANGE
    )

    if (
        negative_daily
        or meaningful_rank_decline
    ):
        return "DETERIORATING"

    return "STABLE"


def determine_sector_cycle(
    *,
    rotation_state: str,
    current_score: int,
    daily_score_change: int | None,
    weekly_score_change: int | None,
    trend: str,
    momentum: str,
) -> str:
    """
    Infer the sector's current analytical cycle.
    """

    if rotation_state in {
        "NEW LEADER",
        "EMERGING",
    }:
        if current_score >= 60:
            return "LEADERSHIP EXPANSION"

        return "EARLY ACCUMULATION"

    if rotation_state == "PERSISTENT LEADER":
        if (
            daily_score_change is not None
            and daily_score_change < 0
        ):
            return "MATURE LEADERSHIP"

        return "LEADERSHIP CONTINUATION"

    if rotation_state == "LOSING LEADERSHIP":
        return "DISTRIBUTION / LEADERSHIP LOSS"

    if rotation_state == "NEW LAGGARD":
        return "BREAKDOWN / DETERIORATION"

    if rotation_state == "PERSISTENT LAGGARD":
        if "IMPROVING" in momentum:
            return "EARLY RECOVERY FROM WEAKNESS"

        return "PERSISTENT WEAKNESS"

    if (
        daily_score_change is not None
        and weekly_score_change is not None
    ):
        if (
            daily_score_change > 0
            and weekly_score_change > 0
        ):
            return "ACCUMULATION"

        if (
            daily_score_change < 0
            and weekly_score_change < 0
        ):
            return "DISTRIBUTION"

        if (
            weekly_score_change < 0
            and daily_score_change > 0
        ):
            return "EARLY RECOVERY"

        if (
            weekly_score_change > 0
            and daily_score_change < 0
        ):
            return "EARLY WEAKENING"

    if "BULLISH" in trend:
        return "POSITIVE CONSOLIDATION"

    if "BEARISH" in trend:
        return "WEAK CONSOLIDATION"

    return "NEUTRAL ROTATION"


def determine_leadership_status(
    *,
    rotation_state: str,
    current_rank: int,
    current_score: int,
) -> str:
    """
    Determine leadership quality.
    """

    if rotation_state == "NEW LEADER":
        return "NEWLY ESTABLISHED LEADERSHIP"

    if rotation_state == "PERSISTENT LEADER":
        return "ESTABLISHED LEADERSHIP"

    if rotation_state == "LOSING LEADERSHIP":
        return "LEADERSHIP UNDER PRESSURE"

    if (
        rotation_state == "EMERGING"
        and current_rank <= LEADING_RANK_LIMIT
    ):
        return "EMERGING LEADERSHIP"

    if current_score >= 55:
        return "CONSTRUCTIVE PARTICIPATION"

    if current_score <= 40:
        return "WEAK PARTICIPATION"

    return "NEUTRAL PARTICIPATION"


def determine_record_rotation_speed(
    *,
    daily_rank_change: int | None,
    daily_score_change: int | None,
) -> str:
    """
    Determine one sector's rotation speed.
    """

    if (
        daily_rank_change is None
        or daily_score_change is None
    ):
        return "INSUFFICIENT HISTORY"

    rank_movement = abs(
        daily_rank_change
    )

    score_movement = abs(
        daily_score_change
    )

    if (
        rank_movement >= 5
        or score_movement >= 12
    ):
        return "VERY FAST"

    if (
        rank_movement >= 3
        or score_movement >= 8
    ):
        return "FAST"

    if (
        rank_movement >= 2
        or score_movement >= 4
    ):
        return "MODERATE"

    return "SLOW"


def determine_record_rotation_risk(
    *,
    rotation_state: str,
    current_risk_level: str,
    daily_rank_change: int | None,
    daily_score_change: int | None,
    weekly_score_change: int | None,
) -> str:
    """
    Determine one sector's rotation risk.
    """

    risk_score = 15

    if current_risk_level == "VERY HIGH":
        risk_score += 35

    elif current_risk_level == "HIGH":
        risk_score += 25

    elif current_risk_level == "MODERATE":
        risk_score += 15

    if rotation_state in {
        "LOSING LEADERSHIP",
        "NEW LAGGARD",
    }:
        risk_score += 25

    if (
        daily_rank_change is not None
        and abs(daily_rank_change) >= 5
    ):
        risk_score += 10

    if (
        daily_score_change is not None
        and weekly_score_change is not None
        and daily_score_change
        * weekly_score_change
        < 0
    ):
        risk_score += 15

    risk_score = clamp_score(
        risk_score
    )

    if risk_score >= 75:
        return "VERY HIGH"

    if risk_score >= 60:
        return "HIGH"

    if risk_score >= 45:
        return "MODERATE"

    if risk_score >= 30:
        return "LOW TO MODERATE"

    return "LOW"


# ==========================================================
# RECORD INTERPRETATION
# ==========================================================

def determine_record_expected_behaviour(
    *,
    rotation_state: str,
    sector_cycle: str,
    current_trend: str,
    current_momentum: str,
) -> str:
    """
    Determine expected sector behaviour.
    """

    if rotation_state == "NEW LEADER":
        return (
            "THE SECTOR MAY ATTRACT INCREASING MARKET ATTENTION, "
            "BUT NEW LEADERSHIP REQUIRES CONFIRMATION"
        )

    if rotation_state == "PERSISTENT LEADER":
        return (
            "THE SECTOR MAY CONTINUE TO LEAD WHILE BREADTH, "
            "MOMENTUM AND RANK REMAIN STABLE"
        )

    if rotation_state == "EMERGING":
        return (
            "THE SECTOR MAY DEVELOP INTO A LEADING GROUP IF "
            "RANK AND BREADTH CONTINUE TO IMPROVE"
        )

    if rotation_state == "LOSING LEADERSHIP":
        return (
            "THE SECTOR MAY UNDERPERFORM RELATIVE TO NEW LEADERS "
            "AS PARTICIPATION AND RANK WEAKEN"
        )

    if rotation_state in {
        "NEW LAGGARD",
        "PERSISTENT LAGGARD",
    }:
        return (
            "THE SECTOR MAY REMAIN UNDER PRESSURE UNTIL BREADTH "
            "AND MOMENTUM SHOW SUSTAINED IMPROVEMENT"
        )

    if sector_cycle == "EARLY RECOVERY":
        return (
            "AN EARLY RECOVERY MAY CONTINUE, BUT LONGER-TERM "
            "ROTATION CONFIRMATION IS REQUIRED"
        )

    if (
        "BULLISH" in current_trend
        and "DETERIORATING" in current_momentum
    ):
        return (
            "THE SECTOR TREND REMAINS POSITIVE, BUT LEADERSHIP "
            "MAY WEAKEN IF MOMENTUM CONTINUES TO DETERIORATE"
        )

    return (
        "THE SECTOR MAY REMAIN STABLE OR ROTATIONAL UNTIL "
        "A CLEARER RANK AND SCORE TREND DEVELOPS"
    )


def build_record_warnings(
    *,
    previous_rank: int | None,
    weekly_rank: int | None,
    rotation_state: str,
    rotation_risk: str,
    current_confidence: int,
) -> tuple[str, ...]:
    """
    Build warnings for one sector.
    """

    warnings: list[str] = []

    if previous_rank is None:
        warnings.append(
            "Daily rank comparison is unavailable."
        )

    if weekly_rank is None:
        warnings.append(
            "Weekly rank comparison is unavailable."
        )

    if rotation_state == "NEW LEADER":
        warnings.append(
            "New leadership has not yet demonstrated persistence."
        )

    if rotation_state == "LOSING LEADERSHIP":
        warnings.append(
            "The sector has moved out of the leading group."
        )

    if rotation_risk in {
        "HIGH",
        "VERY HIGH",
    }:
        warnings.append(
            f"Sector rotation risk is {rotation_risk.lower()}."
        )

    if current_confidence < 60:
        warnings.append(
            "Sector-strength confidence is below 60%."
        )

    if not warnings:
        warnings.append(
            "No major sector-rotation warning is active."
        )

    return tuple(
        dict.fromkeys(warnings)
    )


def build_record_summary(
    *,
    sector: str,
    current_rank: int,
    rotation_state: str,
    daily_rank_change: int | None,
    daily_score_change: int | None,
    sector_cycle: str,
    rotation_risk: str,
) -> str:
    """
    Build a concise sector-rotation summary.
    """

    return (
        f"{sector} | "
        f"RANK {current_rank} | "
        f"{rotation_state} | "
        f"DAILY RANK {format_optional_change(daily_rank_change)} | "
        f"DAILY SCORE {format_optional_change(daily_score_change)} | "
        f"{sector_cycle} | "
        f"{rotation_risk} RISK"
    )


def build_record_explanation(
    *,
    sector: str,
    current_rank: int,
    previous_rank: int | None,
    weekly_rank: int | None,
    current_score: int,
    daily_score_change: int | None,
    weekly_score_change: int | None,
    rotation_state: str,
    sector_cycle: str,
    leadership_status: str,
    rotation_speed: str,
    rotation_risk: str,
) -> str:
    """
    Build the final explanation for one sector.
    """

    return (
        f"{sector} is currently ranked {current_rank}. "
        f"Its previous rank was "
        f"{previous_rank if previous_rank is not None else 'not available'} "
        f"and its weekly-reference rank was "
        f"{weekly_rank if weekly_rank is not None else 'not available'}. "
        f"The current breadth score is {current_score}%, with a daily "
        f"score change of {format_optional_change(daily_score_change)} "
        f"and a weekly score change of "
        f"{format_optional_change(weekly_score_change)}. "
        f"The sector is classified as {rotation_state.lower()}, "
        f"its cycle is {sector_cycle.lower()}, and leadership is "
        f"{leadership_status.lower()}. Rotation speed is "
        f"{rotation_speed.lower()} and rotation risk is "
        f"{rotation_risk.lower()}."
    )


# ==========================================================
# RECORD CREATION
# ==========================================================

def build_rotation_records(
    *,
    current: pd.DataFrame,
    previous: pd.DataFrame | None,
    weekly: pd.DataFrame | None,
) -> tuple[SectorRotationRecord, ...]:
    """
    Build all sector-rotation records.
    """

    previous_map = build_sector_map(
        previous
    )

    weekly_map = build_sector_map(
        weekly
    )

    total_sectors = len(
        current
    )

    records: list[
        SectorRotationRecord
    ] = []

    for _, current_row in current.iterrows():
        sector = str(
            current_row["Sector"]
        )

        previous_row = previous_map.get(
            sector
        )

        weekly_row = weekly_map.get(
            sector
        )

        current_rank = safe_int(
            current_row["Rank"]
        )

        previous_rank = (
            safe_int(
                previous_row["Rank"]
            )
            if previous_row is not None
            else None
        )

        weekly_rank = (
            safe_int(
                weekly_row["Rank"]
            )
            if weekly_row is not None
            else None
        )

        current_score = safe_int(
            current_row["Breadth_Score"]
        )

        previous_score = (
            safe_int(
                previous_row["Breadth_Score"]
            )
            if previous_row is not None
            else None
        )

        weekly_score = (
            safe_int(
                weekly_row["Breadth_Score"]
            )
            if weekly_row is not None
            else None
        )

        daily_rank_change = calculate_rank_change(
            current_rank=current_rank,
            previous_rank=previous_rank,
        )

        weekly_rank_change = calculate_rank_change(
            current_rank=current_rank,
            previous_rank=weekly_rank,
        )

        daily_score_change = calculate_score_change(
            current_score=current_score,
            previous_score=previous_score,
        )

        weekly_score_change = calculate_score_change(
            current_score=current_score,
            previous_score=weekly_score,
        )

        current_strength = normalize_text(
            current_row["Strength"]
        )

        current_trend = normalize_text(
            current_row["Trend"]
        )

        current_momentum = normalize_text(
            current_row["Momentum"]
        )

        current_rotation = normalize_text(
            current_row["Rotation"]
        )

        current_leadership = normalize_text(
            current_row["Leadership"]
        )

        current_risk_level = normalize_text(
            current_row["Risk_Level"]
        )

        current_confidence = safe_int(
            current_row["Confidence"]
        )

        rotation_state = determine_rotation_state(
            current_rank=current_rank,
            previous_rank=previous_rank,
            weekly_rank=weekly_rank,
            current_score=current_score,
            daily_score_change=daily_score_change,
            weekly_score_change=weekly_score_change,
            total_sectors=total_sectors,
        )

        sector_cycle = determine_sector_cycle(
            rotation_state=rotation_state,
            current_score=current_score,
            daily_score_change=daily_score_change,
            weekly_score_change=weekly_score_change,
            trend=current_trend,
            momentum=current_momentum,
        )

        leadership_status = determine_leadership_status(
            rotation_state=rotation_state,
            current_rank=current_rank,
            current_score=current_score,
        )

        rotation_speed = determine_record_rotation_speed(
            daily_rank_change=daily_rank_change,
            daily_score_change=daily_score_change,
        )

        rotation_risk = determine_record_rotation_risk(
            rotation_state=rotation_state,
            current_risk_level=current_risk_level,
            daily_rank_change=daily_rank_change,
            daily_score_change=daily_score_change,
            weekly_score_change=weekly_score_change,
        )

        expected_behaviour = (
            determine_record_expected_behaviour(
                rotation_state=rotation_state,
                sector_cycle=sector_cycle,
                current_trend=current_trend,
                current_momentum=current_momentum,
            )
        )

        warnings = build_record_warnings(
            previous_rank=previous_rank,
            weekly_rank=weekly_rank,
            rotation_state=rotation_state,
            rotation_risk=rotation_risk,
            current_confidence=current_confidence,
        )

        concise_summary = build_record_summary(
            sector=sector,
            current_rank=current_rank,
            rotation_state=rotation_state,
            daily_rank_change=daily_rank_change,
            daily_score_change=daily_score_change,
            sector_cycle=sector_cycle,
            rotation_risk=rotation_risk,
        )

        explanation = build_record_explanation(
            sector=sector,
            current_rank=current_rank,
            previous_rank=previous_rank,
            weekly_rank=weekly_rank,
            current_score=current_score,
            daily_score_change=daily_score_change,
            weekly_score_change=weekly_score_change,
            rotation_state=rotation_state,
            sector_cycle=sector_cycle,
            leadership_status=leadership_status,
            rotation_speed=rotation_speed,
            rotation_risk=rotation_risk,
        )

        records.append(
            SectorRotationRecord(
                sector=sector,

                current_rank=current_rank,
                previous_rank=previous_rank,
                weekly_rank=weekly_rank,

                daily_rank_change=daily_rank_change,
                weekly_rank_change=weekly_rank_change,

                current_score=current_score,
                previous_score=previous_score,
                weekly_score=weekly_score,

                daily_score_change=daily_score_change,
                weekly_score_change=weekly_score_change,

                current_strength=current_strength,
                current_trend=current_trend,
                current_momentum=current_momentum,
                current_rotation=current_rotation,
                current_leadership=current_leadership,
                current_risk_level=current_risk_level,
                current_confidence=current_confidence,

                rotation_state=rotation_state,
                sector_cycle=sector_cycle,
                leadership_status=leadership_status,
                rotation_speed=rotation_speed,
                rotation_risk=rotation_risk,

                expected_behaviour=expected_behaviour,
                concise_summary=concise_summary,
                explanation=explanation,

                warnings=warnings,
                status="SUCCESS",
            )
        )

    return tuple(
        sorted(
            records,
            key=lambda item: item.current_rank,
        )
    )


# ==========================================================
# ENGINE-LEVEL CLASSIFICATION
# ==========================================================

def determine_rotation_direction(
    records: tuple[SectorRotationRecord, ...],
) -> str:
    """
    Determine overall sector-rotation direction.
    """

    improving = sum(
        record.rotation_state
        in {
            "NEW LEADER",
            "EMERGING",
        }
        or (
            record.daily_score_change is not None
            and record.daily_score_change
            >= MINIMUM_MEANINGFUL_SCORE_CHANGE
        )
        for record in records
    )

    deteriorating = sum(
        record.rotation_state
        in {
            "LOSING LEADERSHIP",
            "NEW LAGGARD",
            "DETERIORATING",
        }
        or (
            record.daily_score_change is not None
            and record.daily_score_change
            <= -MINIMUM_MEANINGFUL_SCORE_CHANGE
        )
        for record in records
    )

    difference = (
        improving
        - deteriorating
    )

    if (
        improving >= 7
        and difference >= 4
    ):
        return "BROAD POSITIVE ROTATION"

    if difference >= 2:
        return "SELECTIVE POSITIVE ROTATION"

    if (
        deteriorating >= 7
        and difference <= -4
    ):
        return "BROAD NEGATIVE ROTATION"

    if difference <= -2:
        return "SELECTIVE NEGATIVE ROTATION"

    return "MIXED ROTATION"


def determine_rotation_breadth(
    *,
    records: tuple[SectorRotationRecord, ...],
    improving_count: int,
    deteriorating_count: int,
) -> str:
    """
    Determine how broad rotation is.
    """

    total = len(
        records
    )

    if total == 0:
        return "UNKNOWN"

    moving = (
        improving_count
        + deteriorating_count
    )

    moving_percentage = (
        moving
        / total
        * 100
    )

    if moving_percentage >= 75:
        return "VERY BROAD"

    if moving_percentage >= 55:
        return "BROAD"

    if moving_percentage >= 35:
        return "MODERATE"

    return "NARROW"


def determine_engine_rotation_speed(
    records: tuple[SectorRotationRecord, ...],
) -> str:
    """
    Determine overall rotation speed.
    """

    available = [
        record
        for record in records
        if record.daily_rank_change is not None
        and record.daily_score_change is not None
    ]

    if not available:
        return "INSUFFICIENT HISTORY"

    average_rank_movement = sum(
        abs(record.daily_rank_change or 0)
        for record in available
    ) / len(available)

    average_score_movement = sum(
        abs(record.daily_score_change or 0)
        for record in available
    ) / len(available)

    if (
        average_rank_movement >= 4
        or average_score_movement >= 10
    ):
        return "VERY FAST"

    if (
        average_rank_movement >= 2.5
        or average_score_movement >= 7
    ):
        return "FAST"

    if (
        average_rank_movement >= 1.5
        or average_score_movement >= 4
    ):
        return "MODERATE"

    return "SLOW"


def determine_leadership_stability(
    *,
    records: tuple[SectorRotationRecord, ...],
) -> str:
    """
    Determine persistence of top-sector leadership.
    """

    current_leaders = [
        record
        for record in records
        if is_current_leader(
            record.current_rank
        )
    ]

    if not current_leaders:
        return "UNKNOWN"

    persistent = sum(
        record.rotation_state
        == "PERSISTENT LEADER"
        for record in current_leaders
    )

    new = sum(
        record.rotation_state
        == "NEW LEADER"
        for record in current_leaders
    )

    if persistent == len(
        current_leaders
    ):
        return "VERY STABLE"

    if persistent >= 2:
        return "STABLE"

    if new >= 2:
        return "LEADERSHIP TRANSITION"

    return "MIXED"


def determine_dominant_sector_cycle(
    records: tuple[SectorRotationRecord, ...],
) -> str:
    """
    Determine the most common sector cycle.
    """

    if not records:
        return "UNKNOWN"

    counts: dict[str, int] = {}

    for record in records:
        counts[record.sector_cycle] = (
            counts.get(
                record.sector_cycle,
                0,
            )
            + 1
        )

    return max(
        counts,
        key=counts.get,
    )


def calculate_rotation_risk(
    *,
    records: tuple[SectorRotationRecord, ...],
    rotation_speed: str,
    leadership_stability: str,
    weekly_history_available: bool,
) -> tuple[int, str]:
    """
    Calculate overall sector-rotation risk.
    """

    risk_score = 20.0

    high_risk_sectors = sum(
        record.rotation_risk
        in {
            "HIGH",
            "VERY HIGH",
        }
        for record in records
    )

    if records:
        high_risk_percentage = (
            high_risk_sectors
            / len(records)
            * 100
        )

        risk_score += min(
            high_risk_percentage * 0.45,
            30,
        )

    if rotation_speed == "VERY FAST":
        risk_score += 25

    elif rotation_speed == "FAST":
        risk_score += 15

    elif rotation_speed == "MODERATE":
        risk_score += 7

    if leadership_stability == "LEADERSHIP TRANSITION":
        risk_score += 18

    elif leadership_stability == "MIXED":
        risk_score += 10

    if not weekly_history_available:
        risk_score += 10

    final_score = clamp_score(
        risk_score
    )

    if final_score >= 80:
        risk_level = "VERY HIGH"

    elif final_score >= 65:
        risk_level = "HIGH"

    elif final_score >= 45:
        risk_level = "MODERATE"

    elif final_score >= 25:
        risk_level = "LOW TO MODERATE"

    else:
        risk_level = "LOW"

    return (
        final_score,
        risk_level,
    )


def calculate_engine_confidence(
    *,
    records: tuple[SectorRotationRecord, ...],
    previous_available: bool,
    weekly_available: bool,
) -> int:
    """
    Calculate overall sector-rotation confidence.
    """

    if not records:
        return 0

    average_sector_confidence = sum(
        record.current_confidence
        for record in records
    ) / len(records)

    score = (
        average_sector_confidence
        * 0.70
    )

    if previous_available:
        score += 18

    else:
        score -= 15

    if weekly_available:
        score += 12

    else:
        score -= 5

    if len(records) >= 10:
        score += 5

    return clamp_score(
        score
    )


# ==========================================================
# ENGINE INTERPRETATION
# ==========================================================

def determine_engine_expected_behaviour(
    *,
    rotation_direction: str,
    rotation_speed: str,
    leadership_stability: str,
    rotation_risk_level: str,
) -> str:
    """
    Determine expected behaviour from sector rotation.
    """

    if rotation_direction == "BROAD POSITIVE ROTATION":
        return (
            "BROADER SECTOR PARTICIPATION MAY SUPPORT A MORE "
            "CONSTRUCTIVE MARKET ENVIRONMENT"
        )

    if rotation_direction == "SELECTIVE POSITIVE ROTATION":
        return (
            "SELECTIVE SECTOR LEADERSHIP MAY SUPPORT ROTATIONAL "
            "OR STOCK-SPECIFIC STRENGTH"
        )

    if rotation_direction == "BROAD NEGATIVE ROTATION":
        return (
            "WIDESPREAD SECTOR DETERIORATION MAY SUPPORT A MORE "
            "DEFENSIVE OR RISK-OFF MARKET ENVIRONMENT"
        )

    if rotation_direction == "SELECTIVE NEGATIVE ROTATION":
        return (
            "WEAKNESS MAY REMAIN CONCENTRATED IN SELECTED SECTORS "
            "WHILE LEADERSHIP NARROWS"
        )

    if (
        rotation_speed in {
            "FAST",
            "VERY FAST",
        }
        and leadership_stability
        == "LEADERSHIP TRANSITION"
    ):
        return (
            "RAPID LEADERSHIP CHANGE MAY CREATE VOLATILE AND "
            "SHORT-LIVED SECTOR MOVES"
        )

    if rotation_risk_level in {
        "HIGH",
        "VERY HIGH",
    }:
        return (
            "SECTOR ROTATION MAY REMAIN UNSTABLE AND REQUIRE "
            "CONFIRMATION FROM PRICE, BREADTH AND PARTICIPANT DATA"
        )

    return (
        "SECTOR LEADERSHIP REMAINS MIXED AND THE MARKET MAY "
        "CONTINUE TO ROTATE BETWEEN GROUPS"
    )


def determine_master_conclusion(
    *,
    rotation_direction: str,
    rotation_breadth: str,
    rotation_speed: str,
    leadership_stability: str,
    dominant_sector_cycle: str,
    rotation_risk_level: str,
) -> str:
    """
    Build one final sector-rotation conclusion.
    """

    if rotation_direction == "BROAD POSITIVE ROTATION":
        return (
            "SECTOR LEADERSHIP IS BROADENING POSITIVELY. IMPROVING "
            "PARTICIPATION ACROSS MULTIPLE GROUPS SUPPORTS A MORE "
            "CONSTRUCTIVE MARKET-INTERNAL ENVIRONMENT."
        )

    if rotation_direction == "SELECTIVE POSITIVE ROTATION":
        return (
            "SECTOR ROTATION IS POSITIVE BUT SELECTIVE. MARKET "
            "STRENGTH MAY REMAIN CONCENTRATED IN LEADING AND "
            "EMERGING GROUPS."
        )

    if rotation_direction == "BROAD NEGATIVE ROTATION":
        return (
            "SECTOR PARTICIPATION IS DETERIORATING BROADLY. "
            "LEADERSHIP IS WEAKENING AND MARKET-INTERNAL RISK "
            "REMAINS ELEVATED."
        )

    if rotation_direction == "SELECTIVE NEGATIVE ROTATION":
        return (
            "SECTOR WEAKNESS IS EXPANDING SELECTIVELY. LEADERSHIP "
            "MAY NARROW FURTHER UNLESS EMERGING GROUPS STRENGTHEN."
        )

    return (
        f"SECTOR ROTATION IS MIXED. ROTATION BREADTH IS "
        f"{rotation_breadth}, ROTATION SPEED IS {rotation_speed}, "
        f"LEADERSHIP STABILITY IS {leadership_stability}, AND THE "
        f"DOMINANT CYCLE IS {dominant_sector_cycle}. ROTATION RISK "
        f"IS {rotation_risk_level}."
    )


def build_engine_warnings(
    *,
    previous_date: date | None,
    weekly_reference_date: date | None,
    rotation_speed: str,
    leadership_stability: str,
    rotation_risk_level: str,
) -> tuple[str, ...]:
    """
    Build engine-level warnings.
    """

    warnings: list[str] = []

    if previous_date is None:
        warnings.append(
            "Daily sector-rank comparison is unavailable."
        )

    if weekly_reference_date is None:
        warnings.append(
            "Weekly sector-rank comparison requires at least six "
            "saved sector-strength sessions."
        )

    if rotation_speed in {
        "FAST",
        "VERY FAST",
    }:
        warnings.append(
            "Sector leadership is changing rapidly."
        )

    if leadership_stability == "LEADERSHIP TRANSITION":
        warnings.append(
            "The leading-sector group is undergoing a transition."
        )

    if rotation_risk_level in {
        "HIGH",
        "VERY HIGH",
    }:
        warnings.append(
            f"Overall sector-rotation risk is "
            f"{rotation_risk_level.lower()}."
        )

    if not warnings:
        warnings.append(
            "No major sector-rotation warning is active."
        )

    return tuple(
        dict.fromkeys(warnings)
    )


# ==========================================================
# EXPORT
# ==========================================================

def rotation_records_dataframe(
    records: tuple[SectorRotationRecord, ...],
) -> pd.DataFrame:
    """
    Convert rotation records into a dataframe.
    """

    return pd.DataFrame(
        [
            {
                "Sector": record.sector,

                "Current_Rank": record.current_rank,
                "Previous_Rank": record.previous_rank,
                "Weekly_Rank": record.weekly_rank,

                "Daily_Rank_Change": (
                    record.daily_rank_change
                ),
                "Weekly_Rank_Change": (
                    record.weekly_rank_change
                ),

                "Current_Score": record.current_score,
                "Previous_Score": record.previous_score,
                "Weekly_Score": record.weekly_score,

                "Daily_Score_Change": (
                    record.daily_score_change
                ),
                "Weekly_Score_Change": (
                    record.weekly_score_change
                ),

                "Current_Strength": (
                    record.current_strength
                ),
                "Current_Trend": (
                    record.current_trend
                ),
                "Current_Momentum": (
                    record.current_momentum
                ),
                "Current_Rotation": (
                    record.current_rotation
                ),
                "Current_Leadership": (
                    record.current_leadership
                ),
                "Current_Risk_Level": (
                    record.current_risk_level
                ),
                "Current_Confidence": (
                    record.current_confidence
                ),

                "Rotation_State": (
                    record.rotation_state
                ),
                "Sector_Cycle": record.sector_cycle,
                "Leadership_Status": (
                    record.leadership_status
                ),
                "Rotation_Speed": (
                    record.rotation_speed
                ),
                "Rotation_Risk": (
                    record.rotation_risk
                ),

                "Expected_Behaviour": (
                    record.expected_behaviour
                ),
                "Concise_Summary": (
                    record.concise_summary
                ),
                "Explanation": record.explanation,
                "Status": record.status,
            }
            for record in records
        ]
    )


def format_workbook(
    workbook_path: Path,
) -> None:
    """
    Apply simple formatting to the output workbook.
    """

    from openpyxl import load_workbook
    from openpyxl.styles import Alignment, Font
    from openpyxl.utils import get_column_letter

    workbook = load_workbook(
        workbook_path
    )

    for worksheet in workbook.worksheets:
        worksheet.freeze_panes = "A2"
        worksheet.auto_filter.ref = worksheet.dimensions

        for cell in worksheet[1]:
            cell.font = Font(
                bold=True
            )

            cell.alignment = Alignment(
                horizontal="center",
                vertical="center",
            )

        for column_cells in worksheet.columns:
            maximum_length = 0

            column_number = (
                column_cells[0].column
            )

            for cell in column_cells:
                text = (
                    ""
                    if cell.value is None
                    else str(cell.value)
                )

                maximum_length = max(
                    maximum_length,
                    len(text),
                )

            worksheet.column_dimensions[
                get_column_letter(
                    column_number
                )
            ].width = min(
                max(
                    maximum_length + 2,
                    12,
                ),
                45,
            )

    workbook.save(
        workbook_path
    )


def export_result(
    result: SectorRotationEngineResult,
) -> tuple[Path, Path]:
    """
    Export sector-rotation outputs.
    """

    OUTPUT_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    date_text = result.analysis_date.strftime(
        "%Y%m%d"
    )

    csv_file = (
        OUTPUT_DIRECTORY
        / f"sector_rotation_summary_{date_text}.csv"
    )

    excel_file = (
        OUTPUT_DIRECTORY
        / f"sector_rotation_report_{date_text}.xlsx"
    )

    records_dataframe = rotation_records_dataframe(
        result.records
    )

    summary_dataframe = pd.DataFrame(
        [
            {
                "Requested_Date": result.requested_date,
                "Analysis_Date": result.analysis_date,
                "Previous_Date": result.previous_date,
                "Weekly_Reference_Date": (
                    result.weekly_reference_date
                ),
                "Sectors_Analysed": (
                    result.sectors_analysed
                ),
                "New_Leaders": len(
                    result.new_leaders
                ),
                "Persistent_Leaders": len(
                    result.persistent_leaders
                ),
                "Emerging_Sectors": len(
                    result.emerging_sectors
                ),
                "Losing_Leadership": len(
                    result.losing_leadership
                ),
                "New_Laggards": len(
                    result.new_laggards
                ),
                "Persistent_Laggards": len(
                    result.persistent_laggards
                ),
                "Improving_Sectors": (
                    result.improving_sectors
                ),
                "Deteriorating_Sectors": (
                    result.deteriorating_sectors
                ),
                "Stable_Sectors": (
                    result.stable_sector_count
                ),
                "Rotation_Direction": (
                    result.rotation_direction
                ),
                "Rotation_Breadth": (
                    result.rotation_breadth
                ),
                "Rotation_Speed": (
                    result.rotation_speed
                ),
                "Leadership_Stability": (
                    result.leadership_stability
                ),
                "Dominant_Sector_Cycle": (
                    result.dominant_sector_cycle
                ),
                "Rotation_Risk_Score": (
                    result.rotation_risk_score
                ),
                "Rotation_Risk_Level": (
                    result.rotation_risk_level
                ),
                "Confidence": result.confidence,
                "Expected_Behaviour": (
                    result.expected_behaviour
                ),
                "Master_Conclusion": (
                    result.master_conclusion
                ),
                "Concise_Summary": (
                    result.concise_summary
                ),
                "Explanation": result.explanation,
                "Status": result.status,
            }
        ]
    )

    warnings_dataframe = pd.DataFrame(
        {
            "Warning": list(
                result.warnings
            )
        }
    )

    records_dataframe.to_csv(
        csv_file,
        index=False,
    )

    with pd.ExcelWriter(
        excel_file,
        engine="openpyxl",
    ) as writer:
        summary_dataframe.to_excel(
            writer,
            sheet_name="Summary",
            index=False,
        )

        records_dataframe.to_excel(
            writer,
            sheet_name="All Sectors",
            index=False,
        )

        rotation_records_dataframe(
            result.new_leaders
        ).to_excel(
            writer,
            sheet_name="New Leaders",
            index=False,
        )

        rotation_records_dataframe(
            result.persistent_leaders
        ).to_excel(
            writer,
            sheet_name="Persistent Leaders",
            index=False,
        )

        rotation_records_dataframe(
            result.emerging_sectors
        ).to_excel(
            writer,
            sheet_name="Emerging Sectors",
            index=False,
        )

        rotation_records_dataframe(
            result.losing_leadership
        ).to_excel(
            writer,
            sheet_name="Losing Leadership",
            index=False,
        )

        rotation_records_dataframe(
            result.new_laggards
        ).to_excel(
            writer,
            sheet_name="New Laggards",
            index=False,
        )

        warnings_dataframe.to_excel(
            writer,
            sheet_name="Warnings",
            index=False,
        )

    format_workbook(
        excel_file
    )

    return (
        csv_file,
        excel_file,
    )


# ==========================================================
# MAIN ENGINE
# ==========================================================

def run_sector_rotation_engine(
    *,
    requested_date: date,
    weekly_lookback_sessions: int = (
        DEFAULT_WEEKLY_LOOKBACK_SESSIONS
    ),
    export: bool = True,
) -> SectorRotationEngineResult:
    """
    Run the complete Sector Rotation Engine.
    """

    strength_files = (
        discover_sector_strength_files()
    )

    if not strength_files:
        raise FileNotFoundError(
            "No sector-strength summary files were found in: "
            f"{SECTOR_STRENGTH_DIRECTORY}"
        )

    (
        analysis_date,
        previous_date,
        weekly_reference_date,
    ) = select_analysis_dates(
        requested_date=requested_date,
        available_dates=list(
            strength_files.keys()
        ),
        weekly_lookback_sessions=(
            weekly_lookback_sessions
        ),
    )

    current_dataframe = (
        read_sector_strength_report(
            strength_files[analysis_date]
        )
    )

    previous_dataframe = (
        read_sector_strength_report(
            strength_files[previous_date]
        )
        if previous_date is not None
        else None
    )

    weekly_dataframe = (
        read_sector_strength_report(
            strength_files[
                weekly_reference_date
            ]
        )
        if weekly_reference_date is not None
        else None
    )

    records = build_rotation_records(
        current=current_dataframe,
        previous=previous_dataframe,
        weekly=weekly_dataframe,
    )

    if not records:
        raise RuntimeError(
            "No sector-rotation records were created."
        )

    new_leaders = tuple(
        record
        for record in records
        if record.rotation_state
        == "NEW LEADER"
    )

    persistent_leaders = tuple(
        record
        for record in records
        if record.rotation_state
        == "PERSISTENT LEADER"
    )

    emerging_sectors = tuple(
        record
        for record in records
        if record.rotation_state
        == "EMERGING"
    )

    losing_leadership = tuple(
        record
        for record in records
        if record.rotation_state
        == "LOSING LEADERSHIP"
    )

    new_laggards = tuple(
        record
        for record in records
        if record.rotation_state
        == "NEW LAGGARD"
    )

    persistent_laggards = tuple(
        record
        for record in records
        if record.rotation_state
        == "PERSISTENT LAGGARD"
    )

    stable_sectors = tuple(
        record
        for record in records
        if record.rotation_state
        == "STABLE"
    )

    improving_sectors = sum(
        (
            record.rotation_state
            in {
                "NEW LEADER",
                "EMERGING",
            }
            or (
                record.daily_score_change
                is not None
                and record.daily_score_change
                >= MINIMUM_MEANINGFUL_SCORE_CHANGE
            )
        )
        for record in records
    )

    deteriorating_sectors = sum(
        (
            record.rotation_state
            in {
                "LOSING LEADERSHIP",
                "NEW LAGGARD",
                "DETERIORATING",
            }
            or (
                record.daily_score_change
                is not None
                and record.daily_score_change
                <= -MINIMUM_MEANINGFUL_SCORE_CHANGE
            )
        )
        for record in records
    )

    stable_sector_count = (
        len(records)
        - improving_sectors
        - deteriorating_sectors
    )

    if stable_sector_count < 0:
        stable_sector_count = 0

    rotation_direction = (
        determine_rotation_direction(
            records
        )
    )

    rotation_breadth = determine_rotation_breadth(
        records=records,
        improving_count=improving_sectors,
        deteriorating_count=(
            deteriorating_sectors
        ),
    )

    rotation_speed = (
        determine_engine_rotation_speed(
            records
        )
    )

    leadership_stability = (
        determine_leadership_stability(
            records=records
        )
    )

    dominant_sector_cycle = (
        determine_dominant_sector_cycle(
            records
        )
    )

    (
        rotation_risk_score,
        rotation_risk_level,
    ) = calculate_rotation_risk(
        records=records,
        rotation_speed=rotation_speed,
        leadership_stability=(
            leadership_stability
        ),
        weekly_history_available=(
            weekly_reference_date
            is not None
        ),
    )

    confidence = calculate_engine_confidence(
        records=records,
        previous_available=(
            previous_date is not None
        ),
        weekly_available=(
            weekly_reference_date
            is not None
        ),
    )

    expected_behaviour = (
        determine_engine_expected_behaviour(
            rotation_direction=(
                rotation_direction
            ),
            rotation_speed=rotation_speed,
            leadership_stability=(
                leadership_stability
            ),
            rotation_risk_level=(
                rotation_risk_level
            ),
        )
    )

    master_conclusion = (
        determine_master_conclusion(
            rotation_direction=(
                rotation_direction
            ),
            rotation_breadth=(
                rotation_breadth
            ),
            rotation_speed=rotation_speed,
            leadership_stability=(
                leadership_stability
            ),
            dominant_sector_cycle=(
                dominant_sector_cycle
            ),
            rotation_risk_level=(
                rotation_risk_level
            ),
        )
    )

    concise_summary = (
        f"{rotation_direction} | "
        f"{rotation_breadth} BREADTH | "
        f"{rotation_speed} SPEED | "
        f"{leadership_stability} LEADERSHIP | "
        f"{dominant_sector_cycle} | "
        f"{rotation_risk_level} RISK | "
        f"{confidence}% CONFIDENCE"
    )

    explanation = (
        f"The Sector Rotation Engine analysed {len(records)} sectors. "
        f"{improving_sectors} sectors are improving, "
        f"{deteriorating_sectors} are deteriorating and "
        f"{stable_sector_count} are stable. "
        f"There are {len(new_leaders)} new leaders, "
        f"{len(persistent_leaders)} persistent leaders, "
        f"{len(emerging_sectors)} emerging sectors and "
        f"{len(losing_leadership)} sectors losing leadership. "
        f"Overall rotation is classified as "
        f"{rotation_direction.lower()}, with "
        f"{rotation_breadth.lower()} breadth and "
        f"{rotation_speed.lower()} speed. "
        f"Leadership stability is "
        f"{leadership_stability.lower()}, the dominant sector cycle "
        f"is {dominant_sector_cycle.lower()}, and rotation risk is "
        f"{rotation_risk_level.lower()} at "
        f"{rotation_risk_score}%. Confidence is {confidence}%."
    )

    warnings = build_engine_warnings(
        previous_date=previous_date,
        weekly_reference_date=(
            weekly_reference_date
        ),
        rotation_speed=rotation_speed,
        leadership_stability=(
            leadership_stability
        ),
        rotation_risk_level=(
            rotation_risk_level
        ),
    )

    if previous_date is None:
        overall_status = (
            "INSUFFICIENT HISTORY"
        )

    else:
        overall_status = "SUCCESS"

    result = SectorRotationEngineResult(
        requested_date=requested_date,
        analysis_date=analysis_date,
        previous_date=previous_date,
        weekly_reference_date=(
            weekly_reference_date
        ),

        sectors_analysed=len(records),

        new_leaders=new_leaders,
        persistent_leaders=(
            persistent_leaders
        ),
        emerging_sectors=emerging_sectors,
        losing_leadership=(
            losing_leadership
        ),
        new_laggards=new_laggards,
        persistent_laggards=(
            persistent_laggards
        ),
        stable_sectors=stable_sectors,

        improving_sectors=(
            improving_sectors
        ),
        deteriorating_sectors=(
            deteriorating_sectors
        ),
        stable_sector_count=(
            stable_sector_count
        ),

        rotation_direction=(
            rotation_direction
        ),
        rotation_breadth=rotation_breadth,
        rotation_speed=rotation_speed,
        leadership_stability=(
            leadership_stability
        ),
        dominant_sector_cycle=(
            dominant_sector_cycle
        ),

        rotation_risk_score=(
            rotation_risk_score
        ),
        rotation_risk_level=(
            rotation_risk_level
        ),

        confidence=confidence,
        expected_behaviour=(
            expected_behaviour
        ),
        master_conclusion=(
            master_conclusion
        ),
        concise_summary=concise_summary,
        explanation=explanation,

        records=records,
        warnings=warnings,

        csv_file=None,
        excel_file=None,

        status=overall_status,
    )

    if export:
        csv_file, excel_file = export_result(
            result
        )

        result = SectorRotationEngineResult(
            requested_date=(
                result.requested_date
            ),
            analysis_date=(
                result.analysis_date
            ),
            previous_date=(
                result.previous_date
            ),
            weekly_reference_date=(
                result.weekly_reference_date
            ),

            sectors_analysed=(
                result.sectors_analysed
            ),

            new_leaders=result.new_leaders,
            persistent_leaders=(
                result.persistent_leaders
            ),
            emerging_sectors=(
                result.emerging_sectors
            ),
            losing_leadership=(
                result.losing_leadership
            ),
            new_laggards=(
                result.new_laggards
            ),
            persistent_laggards=(
                result.persistent_laggards
            ),
            stable_sectors=(
                result.stable_sectors
            ),

            improving_sectors=(
                result.improving_sectors
            ),
            deteriorating_sectors=(
                result.deteriorating_sectors
            ),
            stable_sector_count=(
                result.stable_sector_count
            ),

            rotation_direction=(
                result.rotation_direction
            ),
            rotation_breadth=(
                result.rotation_breadth
            ),
            rotation_speed=(
                result.rotation_speed
            ),
            leadership_stability=(
                result.leadership_stability
            ),
            dominant_sector_cycle=(
                result.dominant_sector_cycle
            ),

            rotation_risk_score=(
                result.rotation_risk_score
            ),
            rotation_risk_level=(
                result.rotation_risk_level
            ),

            confidence=result.confidence,
            expected_behaviour=(
                result.expected_behaviour
            ),
            master_conclusion=(
                result.master_conclusion
            ),
            concise_summary=(
                result.concise_summary
            ),
            explanation=result.explanation,

            records=result.records,
            warnings=result.warnings,

            csv_file=csv_file,
            excel_file=excel_file,

            status=result.status,
        )

    return result


# ==========================================================
# DISPLAY HELPERS
# ==========================================================

def display_record_group(
    *,
    heading: str,
    records: tuple[SectorRotationRecord, ...],
) -> None:
    """
    Display one sector-rotation group.
    """

    print(heading)
    print("-" * 116)

    if not records:
        print("None")
        return

    for record in records:
        print(
            f"{record.sector:<35} | "
            f"Rank {record.current_rank:>2} | "
            f"Daily Rank "
            f"{format_optional_change(record.daily_rank_change):>13} | "
            f"Daily Score "
            f"{format_optional_change(record.daily_score_change):>13} | "
            f"{record.rotation_state}"
        )


# ==========================================================
# DISPLAY
# ==========================================================

def display_result(
    result: SectorRotationEngineResult,
) -> None:
    """
    Display the complete MBI-007 result.
    """

    print()
    print("=" * 116)
    print("AQSD SECTOR ROTATION ENGINE")
    print("=" * 116)
    print(f"Module                              : {MODULE_ID}")
    print(f"Version                             : {MODULE_VERSION}")
    print(f"Requested Date                      : {result.requested_date}")
    print(f"Analysis Date                       : {result.analysis_date}")
    print(f"Previous Date                       : {result.previous_date}")
    print(
        f"Weekly Reference Date               : "
        f"{result.weekly_reference_date}"
    )
    print("-" * 116)

    print("ROTATION SUMMARY")
    print("-" * 116)
    print(
        f"Sectors Analysed                    : "
        f"{result.sectors_analysed}"
    )
    print(
        f"Improving Sectors                   : "
        f"{result.improving_sectors}"
    )
    print(
        f"Deteriorating Sectors               : "
        f"{result.deteriorating_sectors}"
    )
    print(
        f"Stable Sectors                      : "
        f"{result.stable_sector_count}"
    )
    print(
        f"New Leaders                         : "
        f"{len(result.new_leaders)}"
    )
    print(
        f"Persistent Leaders                  : "
        f"{len(result.persistent_leaders)}"
    )
    print(
        f"Emerging Sectors                    : "
        f"{len(result.emerging_sectors)}"
    )
    print(
        f"Losing Leadership                   : "
        f"{len(result.losing_leadership)}"
    )
    print(
        f"New Laggards                        : "
        f"{len(result.new_laggards)}"
    )
    print(
        f"Persistent Laggards                 : "
        f"{len(result.persistent_laggards)}"
    )
    print("-" * 116)

    print("ROTATION CLASSIFICATION")
    print("-" * 116)
    print(
        f"Rotation Direction                  : "
        f"{result.rotation_direction}"
    )
    print(
        f"Rotation Breadth                    : "
        f"{result.rotation_breadth}"
    )
    print(
        f"Rotation Speed                      : "
        f"{result.rotation_speed}"
    )
    print(
        f"Leadership Stability                : "
        f"{result.leadership_stability}"
    )
    print(
        f"Dominant Sector Cycle               : "
        f"{result.dominant_sector_cycle}"
    )
    print(
        f"Rotation Risk Score                 : "
        f"{result.rotation_risk_score}%"
    )
    print(
        f"Rotation Risk Level                 : "
        f"{result.rotation_risk_level}"
    )
    print(
        f"Confidence                          : "
        f"{result.confidence}%"
    )
    print("-" * 116)

    display_record_group(
        heading="NEW LEADERS",
        records=result.new_leaders,
    )

    print("-" * 116)

    display_record_group(
        heading="PERSISTENT LEADERS",
        records=result.persistent_leaders,
    )

    print("-" * 116)

    display_record_group(
        heading="EMERGING SECTORS",
        records=result.emerging_sectors,
    )

    print("-" * 116)

    display_record_group(
        heading="LOSING LEADERSHIP",
        records=result.losing_leadership,
    )

    print("-" * 116)

    display_record_group(
        heading="NEW LAGGARDS",
        records=result.new_laggards,
    )

    print("-" * 116)

    display_record_group(
        heading="PERSISTENT LAGGARDS",
        records=result.persistent_laggards,
    )

    print("-" * 116)
    print("ALL SECTOR ROTATION RECORDS")
    print("-" * 116)

    for record in result.records:
        print(
            f"{record.current_rank:>2}. "
            f"{record.sector:<34} | "
            f"Score {record.current_score:>3}% | "
            f"Rank Change "
            f"{format_optional_change(record.daily_rank_change):>13} | "
            f"Score Change "
            f"{format_optional_change(record.daily_score_change):>13} | "
            f"{record.rotation_state}"
        )

    print("-" * 116)
    print("EXPECTED BEHAVIOUR")
    print("-" * 116)
    print(result.expected_behaviour)

    print("-" * 116)
    print("MASTER CONCLUSION")
    print("-" * 116)
    print(result.master_conclusion)

    print("-" * 116)
    print("CONCISE SUMMARY")
    print("-" * 116)
    print(result.concise_summary)

    print("-" * 116)
    print("WARNINGS")
    print("-" * 116)

    for number, warning in enumerate(
        result.warnings,
        start=1,
    ):
        print(
            f"{number}. {warning}"
        )

    print("-" * 116)
    print("EXPLANATION")
    print("-" * 116)
    print(result.explanation)

    print("-" * 116)
    print(
        f"CSV Output                          : "
        f"{result.csv_file}"
    )
    print(
        f"Excel Output                        : "
        f"{result.excel_file}"
    )
    print(
        "Method                              : "
        "RULE-BASED SECTOR ROTATION ANALYSIS"
    )
    print(
        f"Status                              : "
        f"{result.status}"
    )
    print("=" * 116)


# ==========================================================
# COMMAND LINE
# ==========================================================

def parse_date(
    value: str,
) -> date:
    """
    Parse YYYY-MM-DD.
    """

    try:
        return datetime.strptime(
            value,
            "%Y-%m-%d",
        ).date()

    except ValueError as exc:
        raise ValueError(
            "Invalid date format. Use YYYY-MM-DD."
        ) from exc


def parse_arguments() -> argparse.Namespace:
    """
    Read command-line arguments.
    """

    parser = argparse.ArgumentParser(
        description=(
            "Run the AQSD Sector Rotation Engine."
        )
    )

    parser.add_argument(
        "--date",
        required=True,
        help="Requested analysis date in YYYY-MM-DD format.",
    )

    parser.add_argument(
        "--weekly-sessions",
        type=int,
        default=DEFAULT_WEEKLY_LOOKBACK_SESSIONS,
        help=(
            "Number of saved sessions used for the weekly "
            f"comparison. Default: {DEFAULT_WEEKLY_LOOKBACK_SESSIONS}."
        ),
    )

    parser.add_argument(
        "--no-export",
        action="store_true",
        help="Run without creating CSV and Excel outputs.",
    )

    return parser.parse_args()


def main() -> None:
    """
    Command-line entry point.
    """

    arguments = parse_arguments()

    if arguments.weekly_sessions < 1:
        print()
        print("Status : FAILED")
        print("Reason : --weekly-sessions must be at least 1.")
        raise SystemExit(1)

    try:
        result = run_sector_rotation_engine(
            requested_date=parse_date(
                arguments.date
            ),
            weekly_lookback_sessions=(
                arguments.weekly_sessions
            ),
            export=not arguments.no_export,
        )

    except Exception as exc:
        print()
        print("=" * 116)
        print("AQSD SECTOR ROTATION ENGINE")
        print("=" * 116)
        print("Status : FAILED")
        print(f"Reason : {exc}")
        print("=" * 116)

        raise SystemExit(1) from exc

    display_result(
        result
    )


if __name__ == "__main__":
    main()